import requests
import streamlit as st

# Function to upload PDF to ChatPDF API
def upload_pdf_to_chatpdf(file, api_key):
    url = "https://api.chatpdf.com/v1/sources/add-file"
    headers = {'x-api-key': api_key}
    files = {'file': file}
    response = requests.post(url, headers=headers, files=files)
    return response.json()

# Function to generate interview questions from PDF
def generate_interview_questions(source_id, job_description, api_key):
    prompt = f"{job_description} Using both the job description and the resume provided in PDF format, generate potential interview questions that an interviewer might ask a candidate applying for this position. Tailor the questions to reflect the skills, experiences, and qualifications mentioned in both documents. Ensure that the questions are relevant and insightful, taking into account the candidate's background as detailed in the resume."
    url = "https://api.chatpdf.com/v1/chats/message"
    headers = {'x-api-key': api_key, 'Content-Type': 'application/json'}
    data = {
        "sourceId": source_id,
        "messages": [{"role": "user", "content": prompt}]
    }
    response = requests.post(url, headers=headers, json=data)
    return response.json()

def main():
    st.title("Interview Question Generator")
    
    # File upload for PDF
    uploaded_file = st.file_uploader("Upload PDF", type=['pdf'])
    if uploaded_file is not None:
        st.write("PDF uploaded successfully!")
        st.write("Generating interview questions...")
        
        # Job description input
        job_description = st.text_area("Enter Job Description")
        
        if st.button("Generate Questions"):
            # Upload PDF to ChatPDF API
            upload_response = upload_pdf_to_chatpdf(uploaded_file, api_key="sec_AQN91a2YSq04IifX77pVEDiFMMndgbLO")
            if upload_response.get("sourceId"):
                source_id = upload_response["sourceId"]
                # Generate interview questions
                questions_response = generate_interview_questions(source_id, job_description, api_key="sec_AQN91a2YSq04IifX77pVEDiFMMndgbLO")
                if questions_response.get("content"):
                    st.write("Interview questions generated by ChatPDF:")
                    st.write(questions_response["content"])
                else:
                    st.error("Error generating interview questions from PDF")
            else:
                st.error("Error uploading PDF to ChatPDF API")
    else:
        st.write("Upload a PDF file to get started")

if __name__ == "__main__":
    main()